Add placeholder for update

diff --git a/dockerx b/dockerx
--- a/dockerx
+++ b/dockerx
@@ -122,3 +122,9 @@ if [ "$PRINT_VERSION" = true ]; then
 
 	exit 0
 fi
+
+if [ "$UPDATE" = true ]; then
+	# Update DockerX and exit
+	echo 'Error: Update not implemented yet.'
+	exit 1
+fi
