Update dockerx args parsing & handling (#19)

diff --git a/dockerx b/dockerx
--- a/dockerx
+++ b/dockerx
@@ -9,72 +9,358 @@
 
 VERSION='0.1.0'
 
-# Default options
-PRINT_HELP=false
-PRINT_VERSION=false
-UPDATE=false
-CONTEXT_GET=false
-CONTEXT_SET=false
-CONTEXT_NEW_PATH=''
-DRY_RUN=false
-QUIET=false
+ERROR_CODE=''
 
-# Parse options
+# Parse arguments
+# Dummy while loop to allow breaking
 while true; do
-	case "$1" in
-		'--help' | '-h' )
-			# Print help
-			PRINT_HELP=true
-			shift
-			;;
-		'--version' | '-v' )
-			# Print version
-			PRINT_VERSION=true
-			shift
-			;;
-		'--update' )
-			# Update DockerX
-			UPDATE=true
-			shift
-			;;
-		'--get-context' | '-g' | '-c' )
-			# Get context path
-			CONTEXT_GET=true
-			shift
-			;;
-		'--set-context' | '-s' | '-C' )
-			# Set context path
-			CONTEXT_SET=true
-			shift
-			if [ $# -gt 0 ] && [ "$(echo "$1" | cut -c1)" != '-' ]; then
-				CONTEXT_NEW_PATH="$1"
+
+	# Parse options arguments
+	while [ "$#" -gt 0 ]; do
+
+		case "$1" in
+
+			'--help' | '-h' )
+				# Print general help
+				DOCKERX_PRINT_HELP='true'
 				shift
-			fi
-			;;
-		'--reset-context' | '-r' )
-			# Unset context path
-			CONTEXT_SET=true
-			CONTEXT_NEW_PATH='null'
-			shift
-			;;
-		'--dry-run' | '-n' )
-			# Dry run, print docker command without running it
-			DRY_RUN=true
-			shift
-			;;
-		'--quiet' | '-q' )
-			# Quiet, do not print docker command
-			QUIET=true
-			shift
-			;;
-		* )
+				;;
+
+			'--version' | '-v' )
+				# Print version
+				DOCKERX_PRINT_VERSION='true'
+				shift
+				;;
+
+			'--dry-run' | '-n' )
+				# Dry run, print docker command without running it
+				DOCKERX_DRY_RUN='true'
+				shift
+				;;
+
+			'--quiet' | '-q' )
+				# Quiet, do not print docker command
+				DOCKERX_QUIET='true'
+				shift
+				;;
+
+			'--update' )
+				# Update DockerX
+				DOCKERX_UPDATE='true'
+				shift
+				;;
+
+			'--install-dir' | '-i' )
+				shift
+				# Check for installation directory argument
+				if [ -z "$1" ]; then
+					echo 'Error: Missing installation directory.' >&2
+					DOCKERX_PRINT_HELP='true'
+					DOCKERX_UPDATE='true'
+					ERROR_CODE=1
+					break
+				fi
+				# Set installation directory
+				DOCKERX_INSTALL_DIR="$1"
+				shift
+				;;
+
+			'--get-context' | '-g' | '-c' )
+				# Get context path
+				DOCKERX_CONTEXT_GET=true
+				shift
+				;;
+
+			'--set-context' | '-s' | '-C' )
+				# Set context path
+				DOCKERX_CONTEXT_SET=true
+				shift
+				if [ $# -gt 0 ] && [ "$(echo "$1" | cut -c1)" != '-' ]; then
+					DOCKERX_CONTEXT_NEW_PATH="$1"
+					shift
+				fi
+				;;
+
+			'--reset-context' | '-r' )
+				# Unset context path
+				DOCKERX_CONTEXT_SET=true
+				DOCKERX_CONTEXT_NEW_PATH='null'
+				shift
+				;;
+
+			* )
+				break
+				;;
+
+		esac
+
+	done
+
+	if
+		[ "$DOCKERX_PRINT_HELP" = 'true' ] ||
+		[ "$DOCKERX_PRINT_VERSION" = 'true' ] ||
+		[ "$DOCKERX_CONTEXT_GET" = 'true' ] ||
+		[ "$DOCKERX_CONTEXT_SET" = 'true' ]
+	then
+		# Stop parsing arguments
+		break
+	fi
+
+	# Parse first mandatory positional argument
+
+	if [ "$#" -le 0 ] || [ -z "$1" ]; then
+		echo 'Error: No image specified.' >&2
+		DOCKERX_PRINT_HELP='true'
+		ERROR_CODE=1
+		break
+	fi
+
+	if [ "$1" = '?' ]; then
+		# Print general help
+		DOCKERX_PRINT_HELP='true'
+		shift
+		# Stop parsing arguments
+		break
+	fi
+
+	if [ "$1" = 'dockerc' ]; then
+		# Run dockerc command
+		DOCKERX_RUN_DOCKERC='true'
+		shift
+
+	elif [ "$DOCKERX_UPDATE" = 'true' ]; then
+		# Parse update install tag argument
+		DOCKERX_INSTALL_TAG="$1"
+		shift
+		# Stop parsing arguments
+		break
+
+	else
+		# Parse image argument
+		DOCKERX_IMAGE="$1"
+		shift
+	fi
+
+	if [ -n "$DOCKERX_IMAGE" ]; then
+
+		# Check for optional positional arguments
+
+		if [ "$#" -le 0 ]; then
+			# No more arguments
 			break
-			;;
-	esac
+		fi
+
+		# Parse docker options
+
+		PARSE_OPTIONS=''
+		PARSE_OPTIONS_COUNT=0
+		PARSE_OPTIONS_FOUND='false'
+
+		for ARG in "$@"; do
+
+			if [ "$ARG" = '--' ]; then
+				# Found docker options separator
+				PARSE_OPTIONS_FOUND=true
+				break
+			fi
+
+			if [ -z "$ARG" ]; then
+				# Empty argument
+				ARG="''"
+			elif [ "$(echo "$ARG" | grep "[ '\"\$\`;*&#<>|]")" ]; then
+				# Escape argument with spaces or special shell characters
+				# Replace single quotes with escaped single quotes
+				ARG="'$(echo "$ARG" | sed "s/'/'\"'\"'/g")'"
+			fi
+
+			PARSE_OPTIONS="$PARSE_OPTIONS $ARG"
+			PARSE_OPTIONS_COUNT=$((PARSE_OPTIONS_COUNT + 1))
+
+		done
+
+		if [ "$PARSE_OPTIONS_FOUND" = 'true' ]; then
+			# Docker options found
+			while [ "$PARSE_OPTIONS_COUNT" -gt 0 ]; do
+				# Shift docker options from arguments
+				shift
+				PARSE_OPTIONS_COUNT=$((PARSE_OPTIONS_COUNT - 1))
+			done
+			# Shift '--' separator from arguments
+			shift
+			# Save parsed docker options, remove leading space
+			DOCKERX_DOCKER_OPTIONS="${PARSE_OPTIONS# }"
+		fi
+
+		if [ "$#" -le 0 ]; then
+			# No more arguments
+			break
+		fi
+
+		# Parse docker command preset
+		if
+			[ "$1" = '$' ] ||
+			[ "$(echo "$1" | cut -c1)" = '@' ]
+		then
+			if [ "$1" = '@' ]; then
+				# Print docker command preset help
+				DOCKERX_PRINT_HELP_PRESET='true'
+				# Stop parsing arguments
+				break
+			fi
+
+			DOCKERX_DOCKER_PRESET="$1"
+			shift
+		fi
+
+		# Check for optional positional arguments
+		if [ "$#" -le 0 ]; then
+			# No more arguments
+			break
+		fi
+
+	fi
+
+	# Parse trailing positional arguments
+	# Parse command args
+	DOCKERX_COMMAND_ARGS=''
+	for ARG in "$@"; do
+
+		if [ -z "$ARG" ]; then
+			# Empty argument
+			ARG="''"
+		elif [ "$(echo "$ARG" | grep "[ '\"\$\`;*&#<>|]")" ]; then
+			# Escape argument with spaces or special shell characters
+			# Replace single quotes with escaped single quotes
+			ARG="'$(echo "$ARG" | sed "s/'/'\"'\"'/g")'"
+		fi
+
+		DOCKERX_COMMAND_ARGS="$DOCKERX_COMMAND_ARGS $ARG"
+
+	done
+
+	# Remove leading space
+	DOCKERX_COMMAND_ARGS="${DOCKERX_COMMAND_ARGS# }"
+
+	# Stop parsing arguments
+	break
+
 done
 
-if [ "$PRINT_HELP" = true ]; then
-	# Print help and exit
+if [ "$DOCKERX_DEBUG_ARGS" = 'true' ]; then
+	# Print parsed arguments
+	echo "DOCKERX_PRINT_HELP: $DOCKERX_PRINT_HELP"
+	echo "DOCKERX_PRINT_HELP_PRESET: $DOCKERX_PRINT_HELP_PRESET"
+	echo "DOCKERX_DRY_RUN: $DOCKERX_DRY_RUN"
+	echo "DOCKERX_QUIET: $DOCKERX_QUIET"
+	echo "DOCKERX_UPDATE: $DOCKERX_UPDATE"
+	echo "DOCKERX_INSTALL_DIR: $DOCKERX_INSTALL_DIR"
+	echo "DOCKERX_CONTEXT_GET: $DOCKERX_CONTEXT_GET"
+	echo "DOCKERX_CONTEXT_SET: $DOCKERX_CONTEXT_SET"
+	echo "DOCKERX_CONTEXT_NEW_PATH: $DOCKERX_CONTEXT_NEW_PATH"
+	echo "DOCKERX_INSTALL_TAG: $DOCKERX_INSTALL_TAG"
+	echo "DOCKERX_RUN_DOCKERC: $DOCKERX_RUN_DOCKERC"
+	echo "DOCKERX_IMAGE: $DOCKERX_IMAGE"
+	echo "DOCKERX_DOCKER_OPTIONS: $DOCKERX_DOCKER_OPTIONS"
+	echo "DOCKERX_DOCKER_PRESET: $DOCKERX_DOCKER_PRESET"
+	echo "DOCKERX_COMMAND_ARGS: $DOCKERX_COMMAND_ARGS"
+	exit ${ERROR_CODE:-0}
+fi
+
+DRY_RUN='false'
+if [ -n "$DOCKERX_DRY_RUN" ]; then
+	# Use from argument or environment variable
+	DRY_RUN="$DOCKERX_DRY_RUN"
+fi
+
+QUIET='false'
+if [ -n "$DOCKERX_QUIET" ]; then
+	# Use from argument or environment variable
+	QUIET="$DOCKERX_QUIET"
+fi
+
+UPDATE='false'
+if [ -n "$DOCKERX_UPDATE" ]; then
+	# Use from argument or environment variable
+	UPDATE="$DOCKERX_UPDATE"
+fi
+
+INSTALL_DIR="$(dirname "$0")"
+if [ -n "$DOCKERX_INSTALL_DIR" ]; then
+	# Use from argument or environment variable
+	INSTALL_DIR="$DOCKERX_INSTALL_DIR"
+fi
+
+CONTEXT_GET=''
+if [ -n "$DOCKERX_CONTEXT_GET" ]; then
+	# Use from argument or environment variable
+	CONTEXT_GET="$DOCKERX_CONTEXT_GET"
+fi
+
+CONTEXT_SET=''
+if [ -n "$DOCKERX_CONTEXT_SET" ]; then
+	# Use from argument or environment variable
+	CONTEXT_SET="$DOCKERX_CONTEXT_SET"
+fi
+
+CONTEXT_NEW_PATH=''
+if [ -n "$DOCKERX_CONTEXT_NEW_PATH" ]; then
+	# Use from argument or environment variable
+	CONTEXT_NEW_PATH="$DOCKERX_CONTEXT_NEW_PATH"
+fi
+
+INSTALL_TAG=''
+if [ -n "$DOCKERX_INSTALL_TAG" ]; then
+	# Use from argument or environment variable
+	INSTALL_TAG="$DOCKERX_INSTALL_TAG"
+fi
+
+RUN_DOCKERC='false'
+if [ -n "$DOCKERX_RUN_DOCKERC" ]; then
+	# Use from argument or environment variable
+	RUN_DOCKERC="$DOCKERX_RUN_DOCKERC"
+fi
+
+IMAGE=''
+if [ -n "$DOCKERX_IMAGE" ]; then
+	# Use from argument or environment variable
+	IMAGE="$DOCKERX_IMAGE"
+fi
+
+DOCKER_OPTIONS=''
+if [ -n "$DOCKERX_DOCKER_OPTIONS" ]; then
+	# Use from argument or environment variable
+	DOCKER_OPTIONS="$DOCKERX_DOCKER_OPTIONS"
+fi
+
+DOCKER_PRESET=''
+if [ -n "$DOCKERX_DOCKER_PRESET" ]; then
+	# Use from argument or environment variable
+	DOCKER_PRESET="$DOCKERX_DOCKER_PRESET"
+fi
+
+COMMAND_ARGS=''
+if [ -n "$DOCKERX_COMMAND_ARGS" ]; then
+	# Use from argument or environment variable
+	COMMAND_ARGS="$DOCKERX_COMMAND_ARGS"
+fi
+
+if [ "$DOCKERX_PRINT_HELP" = 'true' ]; then
+
+	if [ "$UPDATE" = 'true' ]; then
+		# Print update help & exit
+		echo "Usage: $0 --update [options] [tag]"
+		echo ''
+		echo 'Options:'
+		echo '  -h, --help         Print this help message'
+		echo '  -i, --install-dir  Set installation directory'
+		echo "    (defaults to directory '$(dirname "$0")')"
+		echo ''
+		echo 'Arguments:'
+		echo '  tag  DockerX tag/version to install (defaults to HEAD)'
+		exit ${ERROR_CODE:-0}
+	fi
+
+	# Print help & exit
 	echo 'Usage:'
 	echo "  $0 [options] <image> [ [...docker_options] -- ] [...command]"
 	echo "  $0 [options] <image> [ [...docker_options] -- ] [@preset] [...args]"
@@ -103,10 +389,17 @@ if [ "$PRINT_HELP" = true ]; then
 	echo '    -q, --quiet          Quiet, do not print docker command'
 	echo '  @preset: One of the following:'
 	echo '    $, @sh  Run a `sh` shell in the container'
+	exit ${ERROR_CODE:-0}
+fi
+
+if [ "$DOCKERX_PRINT_HELP_PRESET" = 'true' ]; then
+	# Print docker command preset help & exit
+	echo "Use $0 --help for full help"
+	echo 'DockerX command presets:'
+	echo '  $, @sh  Run a `sh` shell in the container'
 	exit 0
 fi
 
-# Function to get latest version
 get_latest_version() {
 	# Syntax: '"tag_name": "v1.0.0",'
 	LATEST_VERSION_JSON=$(
@@ -115,29 +408,31 @@ get_latest_version() {
 	)
 
 	if [ -n "$LATEST_VERSION_JSON" ]; then
+		# Extract version from matched string
+		# Remove `"tag_name": "` (13 characters) and `",` (2 characters)
 		if [ "$(uname -s)" = 'Darwin' ]; then
 			# MacOS
-			LATEST_VERSION="${LATEST_VERSION_JSON:14:$((${#LATEST_VERSION_JSON}-14-2))}"
+			LATEST_VERSION="${LATEST_VERSION_JSON:13:$((${#LATEST_VERSION_JSON}-13-2))}"
 		else
 			# Linux
-			LATEST_VERSION=$(expr substr "$LATEST_VERSION_JSON" $(expr 1 + 14) $(expr length "$LATEST_VERSION_JSON" - 14 - 2))
+			LATEST_VERSION=$(expr substr "$LATEST_VERSION_JSON" $(expr 1 + 13) $(expr length "$LATEST_VERSION_JSON" - 13 - 2))
 		fi
 
 		echo "$LATEST_VERSION"
 	fi
 }
 
-if [ "$PRINT_VERSION" = true ]; then
+if [ "$DOCKERX_PRINT_VERSION" = 'true' ]; then
+	# Print version & exit
 
-	# Print version and exit
-	if [ "$QUIET" = false ]; then
+	if [ "$QUIET" = 'false' ]; then
 		echo "DockerX (v$VERSION) - https://github.com/matiboux/dockerx"
 
-		if [ "$DRY_RUN" = false ]; then
+		if [ "$DRY_RUN" = 'false' ]; then
 			LATEST_VERSION=$(get_latest_version)
 			if [ -z "$LATEST_VERSION" ]; then
-				echo 'Warning: Could not determine latest version.' >&2
-			elif [ "$VERSION" != "$LATEST_VERSION" ]; then
+				echo 'Notice: Failed to get DockerX latest version.' >&2
+			elif [ "$VERSION" != "${LATEST_VERSION#v}" ]; then
 				echo "Notice: DockerX is not up to date, latest version is $LATEST_VERSION!" >&2
 			fi
 		fi
@@ -146,13 +441,32 @@ if [ "$PRINT_VERSION" = true ]; then
 		echo "v$VERSION"
 	fi
 
-	exit 0
+	exit ${ERROR_CODE:-0}
 fi
 
-if [ "$UPDATE" = true ]; then
-	# Update DockerX and exit
-	echo 'Error: Update not implemented yet.' >&2
-	exit 1
+if [ "$UPDATE" = 'true' ]; then
+	# Update DockerX & exit
+
+	INSTALL_TAG_ARG=''
+	if [ -n "$INSTALL_TAG" ]; then
+		INSTALL_TAG_ARG=" \"$INSTALL_TAG\""
+	fi
+
+	if [ "$QUIET" = 'false' ]; then
+		# Print install script command
+		if [ "$DOCKERX_FIRST_NEWLINE" != 'false' ]; then
+			echo ''
+		fi
+		echo "> curl -fsSL \"https://raw.githubusercontent.com/matiboux/dockerx/HEAD/install.sh\" | /bin/sh -s -- --install-dir \"${INSTALL_DIR}\"${INSTALL_TAG_ARG}"
+		echo ''
+	fi
+
+	if [ "$DRY_RUN" = 'false' ]; then
+		# Run install script command
+		exec sh -c "curl -fsSL \"https://raw.githubusercontent.com/matiboux/dockerx/HEAD/install.sh\" | /bin/sh -s -- --install-dir \"${INSTALL_DIR}\"${INSTALL_TAG_ARG}"
+	fi
+
+	exit ${ERROR_CODE:-0}
 fi
 
 # Get dockerx context path file
@@ -187,7 +501,8 @@ else
 	CONTEXT_PATH=''
 fi
 
-if [ "$CHECK_PARENT_CONTEXT" = 'true' ] &&
+if
+	[ "$CHECK_PARENT_CONTEXT" = 'true' ] &&
 	[ -d "$CONTEXT_PATH" ] &&
 	echo "$(pwd)" | grep -qv "^$(echo "$CONTEXT_PATH" | sed 's/[\/]\?$//')"
 then
@@ -212,6 +527,7 @@ if [ -z "$CONTEXT_PATH" ] || [ ! -d "$CONTEXT_PATH" ]; then
 		echo "Warning: Context path '$CONTEXT_PATH' not found, using current directory" >&2
 	fi
 
+	# Use current directory as context path
 	CONTEXT_PATH_SOURCE='DEFAULT'
 	CONTEXT_PATH="$(pwd)"
 fi
@@ -276,37 +592,12 @@ if [ "$CONTEXT_SET" = true ]; then
 	exit 0
 fi
 
-# Get image
-if [ $# -eq 0 ] || [ -z "$1" ]; then
-	echo 'Error: No image specified' >&2
-	exit 1
-fi
-
-DOCKER_IMAGE="$1"
-shift
-
-if [ "$DOCKER_IMAGE" = 'dockerc' ]; then
+if [ "$RUN_DOCKERC" = 'true' ]; then
 	# Run dockerc command with following arguments
 
-	# Get arguments
-	ARGS=''
-	if [ $# -gt 0 ]; then
-		for ARG in "$@"; do
-
-			if [ -z "$ARG" ]; then
-				# Skip empty arguments
-				continue
-			fi
-
-			if [ "$(echo "$ARG" | grep "[ '\"\$\`;*&#<>|]")" ]; then
-				# Escape argument with spaces or special shell characters
-				# Replace single quotes with escaped single quotes
-				ARG="'$(echo "$ARG" | sed "s/'/'\"'\"'/g")'"
-			fi
-
-			ARGS="$ARGS $ARG"
-
-		done
+	# Format variables with leading space
+	if [ -n "$COMMAND_ARGS" ]; then
+		COMMAND_ARGS=" $COMMAND_ARGS"
 	fi
 
 	if [ "$QUIET" = false ]; then
@@ -314,147 +605,68 @@ if [ "$DOCKER_IMAGE" = 'dockerc' ]; then
 		if [ "$DOCKERX_FIRST_NEWLINE" != 'false' ]; then
 			echo ''
 		fi
-		echo "> cd '$CONTEXT_PATH'"
-		echo "> dockerc$ARGS"
+		echo "> cd '${CONTEXT_PATH}'"
+		echo "> dockerc${COMMAND_ARGS}"
 		echo ''
 	fi
 
 	if [ "$DRY_RUN" = false ]; then
 		# Run dockerc command
 		export DOCKERC_FIRST_NEWLINE='false'
-		exec sh -c "cd \"$CONTEXT_PATH\" && dockerc$ARGS"
+		exec sh -c "cd \"${CONTEXT_PATH}\" && dockerc${COMMAND_ARGS}"
 	fi
 
 	exit 0
-fi
-
-# Get docker options
-DOCKER_OPTIONS=''
-DOCKER_OPTIONS_COUNT=0
-FOUND_DOCKER_OPTIONS=false
-if [ $# -gt 0 ]; then
-	for ARG in "$@"; do
-
-		if [ -z "$ARG" ]; then
-			# Skip empty arguments
-			continue
-		fi
-
-		if [ "$ARG" = '--' ]; then
-			# Found docker options separator
-			FOUND_DOCKER_OPTIONS=true
-			break
-		fi
-
-		if [ "$(echo "$ARG" | grep "[ '\"\$\`;*&#<>|]")" ]; then
-			# Escape argument with spaces or special shell characters
-			# Replace single quotes with escaped single quotes
-			ARG="'$(echo "$ARG" | sed "s/'/'\"'\"'/g")'"
-		fi
-
-		DOCKER_OPTIONS="$DOCKER_OPTIONS $ARG"
-		DOCKER_OPTIONS_COUNT=$((DOCKER_OPTIONS_COUNT + 1))
-
-	done
-fi
-
-if [ "$FOUND_DOCKER_OPTIONS" = true ]; then
-	# Docker options found
-	while [ $DOCKER_OPTIONS_COUNT -gt 0 ]; do
-		# Remove docker options from arguments
-		shift
-		DOCKER_OPTIONS_COUNT=$((DOCKER_OPTIONS_COUNT - 1))
-	done
-	# Remove '--' separator from arguments
-	shift
-else
-	# Docker options not found
-	# Arguments are commands, not options
-	DOCKER_OPTIONS=''
-	DOCKER_OPTIONS_COUNT=0
 fi
 
 # Prepend DockerX docker options
+if [ -n "$DOCKER_OPTIONS" ]; then
+	DOCKER_OPTIONS=" $DOCKER_OPTIONS"
+fi
 DOCKER_OPTIONS="-it --rm -v '$CONTEXT_PATH:/workdir' -w /workdir$DOCKER_OPTIONS"
 
-# Get command
-PRINT_COMMAND_PRESET_HELP='false'
-COMMAND=''
-if [ $# -gt 0 ]; then
-	# Check for arguments preset
-	COMMAND_PRESET=''
-	if [ "$1" = '@' ]; then
-		PRINT_COMMAND_PRESET_HELP='true'
-		shift
-	elif [ "$1" = '$' ]; then
-		COMMAND_PRESET="@sh"
-		shift
-	elif [ "$(echo "$1" | cut -c1)" = '@' ]; then
-		if [ "$(echo "$1" | cut -c2)" = '@' ]; then
-			# Escape command preset
-			COMMAND="${1#?}"
-			shift
-		else
-			COMMAND_PRESET="$1"
-			shift
+# Handle docker command preset
+DOCKER_ARGS=''
+if [ -n "$DOCKER_PRESET" ]; then
+
+	if [ "$(echo "$DOCKER_PRESET" | cut -c1-2)" = '@@' ]; then
+		# Escape pattern: Remove '@' prefix & use in docker command
+		DOCKER_ARGS="${DOCKER_PRESET#@}"
+		if [ "$(echo "$DOCKER_ARGS" | grep "[ '\"\$\`;*&#<>|]")" ]; then
+			# Escape argument with spaces or special shell characters
+			# Replace single quotes with escaped single quotes
+			DOCKER_ARGS="'$(echo "$DOCKER_ARGS" | sed "s/'/'\"'\"'/g")'"
 		fi
-	fi
 
-	if [ -n "$COMMAND_PRESET" ]; then
-		# Parse command preset
-		case "${COMMAND_PRESET#?}" in
+	else
+		case "$DOCKER_PRESET" in
 
-			'sh' )
-				COMMAND='sh'
+			'@sh' )
+				DOCKER_ARGS='sh'
 				;;
-
-			*)
-				echo "Error: Unknown command preset '$COMMAND_PRESET'" >&2
-				exit 1
+			'@$' )
+				DOCKER_ARGS='sh'
+				;;
+			'$' )
+				DOCKER_ARGS='sh'
 				;;
 
 		esac
-	fi
-fi
 
-if [ "$PRINT_COMMAND_PRESET_HELP" = true ]; then
-	# Print command presets help and exit
-	echo "Use $0 --help for full help"
-	echo 'DockerX command presets:'
-	echo '  $, @sh  Run a `sh` shell in the container'
-	exit 0
-fi
-
-if [ -n "$COMMAND" ]; then
-	if [ "$(echo "$COMMAND" | grep "[ '\"\$\`;*&#<>|]")" ]; then
-		# Escape argument with spaces or special shell characters
-		# Replace single quotes with escaped single quotes
-		COMMAND="'$(echo "$COMMAND" | sed "s/'/'\"'\"'/g")'"
+		if [ -z "$DOCKER_ARGS" ]; then
+			echo "Error: Unknown docker command preset '$DOCKER_PRESET'" >&2
+			exit 1
+		fi
 	fi
 
-	# Add leading space
-	COMMAND=" $COMMAND"
 fi
 
-# Get arguments
-ARGS=''
-if [ $# -gt 0 ]; then
-	for ARG in "$@"; do
-
-		if [ -z "$ARG" ]; then
-			# Skip empty arguments
-			continue
-		fi
-
-		if [ "$(echo "$ARG" | grep "[ '\"\$\`;*&#<>|]")" ]; then
-			# Escape argument with spaces or special shell characters
-			# Replace single quotes with escaped single quotes
-			ARG="'$(echo "$ARG" | sed "s/'/'\"'\"'/g")'"
-		fi
-
-		ARGS="$ARGS $ARG"
-
-	done
+# Format variables with leading space
+if [ -n "$DOCKER_ARGS" ]; then
+	DOCKER_ARGS=" $DOCKER_ARGS"
+fi
+if [ -n "$COMMAND_ARGS" ]; then
+	COMMAND_ARGS=" $COMMAND_ARGS"
 fi
 
 if [ "$QUIET" = false ]; then
@@ -462,11 +674,11 @@ if [ "$QUIET" = false ]; then
 	if [ "$DOCKERX_FIRST_NEWLINE" != 'false' ]; then
 		echo ''
 	fi
-	echo "> docker run $DOCKER_OPTIONS $DOCKER_IMAGE$COMMAND$ARGS"
+	echo "> docker run ${DOCKER_OPTIONS} ${IMAGE}${DOCKER_ARGS}${COMMAND_ARGS}"
 	echo ''
 fi
 
 if [ "$DRY_RUN" = false ]; then
 	# Run docker command
-	exec sh -c "docker run $DOCKER_OPTIONS $DOCKER_IMAGE$COMMAND$ARGS"
+	exec sh -c "docker run ${DOCKER_OPTIONS} ${IMAGE}${DOCKER_ARGS}${COMMAND_ARGS}"
 fi
