Check context path is a parent directory (#8)

diff --git a/dockerx b/dockerx
--- a/dockerx
+++ b/dockerx
@@ -175,9 +175,24 @@ elif [ -n "$CONTEXT_PATH" ]; then
 elif [ -f "$CONTEXT_FILE" ]; then
 	CONTEXT_PATH_SOURCE='FILE'
 	CONTEXT_PATH="$(cat "$CONTEXT_FILE")"
+else
+	CONTEXT_PATH_SOURCE=''
+	CONTEXT_PATH=''
 fi
 
-if [ ! -d "$CONTEXT_PATH" ]; then
+if [ -d "$CONTEXT_PATH" ] && echo "$(pwd)" | grep -qv "^$(echo "$CONTEXT_PATH" | sed 's/[\/]\?$//')"; then
+	# Context path is not a parent directory of the current directory
+	if [ "$CONTEXT_PATH_SOURCE" = 'ENV' ]; then
+		echo "Error: Context path '$CONTEXT_PATH' is not a parent directory"
+		exit 1
+	fi
+
+	# Clear context path
+	CONTEXT_PATH_SOURCE=''
+	CONTEXT_PATH=''
+fi
+
+if [ -z "$CONTEXT_PATH" ] || [ ! -d "$CONTEXT_PATH" ]; then
 	if [ "$CONTEXT_PATH_SOURCE" = 'ENV' ]; then
 		echo "Error: Context path '$CONTEXT_PATH' not found"
 		exit 1
@@ -205,6 +220,8 @@ if [ "$CONTEXT_GET" = true ]; then
 		echo '(from environment variable)'
 	elif [ "$CONTEXT_PATH_SOURCE" = 'FILE' ]; then
 		echo '(from .dockerx file)'
+	elif [ "$CONTEXT_PATH_SOURCE" = 'DEFAULT' ]; then
+		echo '(current directory)'
 	fi
 
 	exit 0
